### ISSUE TITLE
API documentation reference for Bitbucket code coverage

### ISSUE THREAD

**Issue by jxpose** [T45K/Bitbucket-Server-Code-Insights-plugin#256]
Hello Task-san,

This is John and Im so impressed with this personal project.
I was studying this and I am a bit lost on the API reference for sending code coverage.
https://github.com/T45K/Bitbucket-Server-Code-Insights-plugin/blob/master/src/main/kotlin/io/jenkins/plugins/codeInsights/infrastructure/HttpClient.kt#L131

I tried looking for the reference but can't find it.
I might have missed it but in case can share to me the reference where to find it if you have.

Regards,
John

**Comment by T45K** [comment]
thank you for asking

first, unfortunately, code coverage highlight feature is not an official feature of Bitbucket (it is just one of plugins), so there is no official API doc for the feature.

https://marketplace.atlassian.com/apps/1218271/code-coverage-for-bitbucket

when i developed this plugin, i referred to the following repository, which looks sample usage of the feature from Atlassian.

https://bitbucket.org/atlassian/bitbucket-code-coverage/issues?status=new&status=open

but now, they seemed to hide source code, so no longer we can refer the impl...

if you need more info, please ask admin of Bitbucker server of you company 🙏 

regards,

**Comment by jxpose** [comment]
Thank you very much for the response

I understand the situation. 
Though it's unfortunate, I don't think there's much that can be done about it.😅 .
I'll close the issue.

Thanks
